######################################################################
# Automatically generated by qmake (3.0) ? 9? 13 15:59:00 2015
######################################################################

TEMPLATE = app
TARGET = fesgame
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
