######################################################################
# Automatically generated by qmake (3.0) ? 9? 13 10:57:33 2015
######################################################################

TEMPLATE = app
TARGET = fesgame
INCLUDEPATH += .

# Input
SOURCES += mainwindow.cpp
